from pygame.constants import USEREVENT
from pygame.locals import USEREVENT

#--- MENU EVENTS ---#
MENU_BASE = USEREVENT + 0
MAIN_MENU = MENU_BASE + 1
SINGLEPLAYER_MENU = MENU_BASE + 2
MULTIPLATER_MENU = MENU_BASE + 3

#--- GAME EVENTS ---#
GAME_BASE = USEREVENT + 100
START_SINGLEPLAYER = GAME_BASE + 1
FINISHED = GAME_BASE + 2